"""Generating LLM node: new items from each input item.

The shell behind HyDE, query expansion, and planner-shaped flows: one
structured call per input item whose designated string-list field becomes
new items. N generated queries flow straight into the retrievers' existing
multi-query fan-out and fusion.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import Field

from app.pipelines.definition import PipelineDefinition, PipelineNodeDefinition
from app.pipelines.execution.context import PipelineRunContext
from app.pipelines.llm.config import LlmNodeConfig
from app.pipelines.llm.engine import LlmCall, LlmEngine
from app.pipelines.llm.mapping import generated_texts, items_field
from app.pipelines.llm.output_schema import (
    LlmOutputError,
    per_item_schema,
    validate_fields,
)
from app.pipelines.llm.presets import GENERATE_PRESETS
from app.pipelines.llm.prompts import PromptContext, render
from app.pipelines.llm.summaries import llm_call_summary_values
from app.pipelines.llm.validation import GENERATE_TARGETS, ShellRules, shell_issues
from app.pipelines.node import PipelineNodeBase, PipelineValidationIssue
from app.pipelines.payloads import Item, ItemBatch, trace_items
from app.pipelines.ports import Facet, NodePort, PortKind
from app.pipelines.tracing import NodeTraceSummary, NodeTraceValue
from app.pipelines.tracing.summaries import combine_usage

if TYPE_CHECKING:
    from app.pipelines.registry import NodeRegistry

_RULES = ShellRules(
    node_label="LLM generator",
    allowed_targets=GENERATE_TARGETS,
    allowed_placeholders=frozenset({"text", "query"}),
    requires_items_field=True,
)


class LlmGenerateConfig(LlmNodeConfig):
    """Generator config: the shared LLM contract plus source passthrough."""

    include_original: bool = Field(
        default=False,
        description="Also pass each source item through alongside what it generated.",
    )


class LlmGenerateNode(PipelineNodeBase[LlmGenerateConfig]):
    """Emit new items generated by a structured LLM call per input item."""

    type = "llm.generate"
    label = "LLM Generator"
    category = "llm"
    description = (
        "Generate new items from each input item with a structured LLM call — "
        "rewritten queries, hypothetical passages, sub-queries."
    )
    example = "Items([query]) -> Items([rewrite_1, rewrite_2, rewrite_3])."
    input_ports = (
        NodePort(
            key="items",
            label="Items",
            data_type=PortKind.ITEMS,
            requires=(Facet.TEXT,),
        ),
    )
    output_ports = (
        NodePort(
            key="items",
            label="Generated items",
            data_type=PortKind.ITEMS,
            adds=(Facet.TEXT,),
        ),
    )
    config_model = LlmGenerateConfig
    presets = GENERATE_PRESETS

    def __init__(self, config: LlmGenerateConfig) -> None:
        """Initialize the node and its per-run trace stash."""
        super().__init__(config)
        self._warnings: list[str] = []
        self._retries = 0
        self._mechanism: str | None = None

    @classmethod
    def validation_issues_for_node(
        cls,
        node: PipelineNodeDefinition,
        definition: PipelineDefinition,
        _registry: NodeRegistry,
    ) -> list[PipelineValidationIssue]:
        """Check config completeness, targets, and prompt placeholders."""
        config = LlmGenerateConfig.model_validate(node.config or {})
        return shell_issues(node, definition, config, _RULES)

    def run(self, inputs: dict[str, object], context: PipelineRunContext) -> dict[str, object]:
        """Generate items per source; degrade to the source item itself."""
        batch = ItemBatch.model_validate(inputs.get("items"))
        if not batch.items:
            return {"items": batch}
        engine = LlmEngine(
            context.providers,
            self.config,
            node_label=self.label,
            strict=context.document is not None,
        )
        self._mechanism = engine.mechanism
        fields = self.config.output_fields
        source_field = items_field(fields)
        if source_field is None:  # validation blocks this; honest error if reached
            raise LlmOutputError("LLM generator has no output field targeting 'items'.")
        schema = per_item_schema(fields)
        calls = []
        for item in batch.items:
            prompt_context = PromptContext(
                text=item.text,
                query=context.query,
                metadata=dict(item.metadata.data),
            )
            calls.append(
                LlmCall(
                    system=render(self.config.system_prompt, prompt_context),
                    user=render(self.config.prompt, prompt_context),
                )
            )
        outcomes = engine.run_calls(calls, schema, lambda payload: validate_fields(payload, fields))
        items: list[Item] = []
        for source, outcome in zip(batch.items, outcomes, strict=True):
            if self.config.include_original or outcome.values is None:
                # A failed generation degrades to the source item — the query
                # still retrieves as itself rather than not at all.
                items.append(source)
            if outcome.values is None:
                continue
            for index, text in enumerate(generated_texts(source_field, outcome.values), 1):
                items.append(
                    Item(
                        id=f"{source.id}:llm{index}",
                        text=text,
                        metadata=source.metadata,
                    )
                )
        self._warnings = engine.warnings
        self._retries = sum(outcome.retries for outcome in outcomes)
        usage = combine_usage([batch.usage, engine.combined_usage(outcomes)])
        return {"items": ItemBatch(items=items, tokenizer=batch.tokenizer, usage=usage)}

    def summarize_io(
        self,
        inputs: dict[str, object],
        outputs: dict[str, object],
    ) -> NodeTraceSummary:
        """Summarize sources, generated items, and the calls that made them."""
        input_batch = ItemBatch.model_validate(inputs.get("items"))
        output_batch = ItemBatch.model_validate(outputs.get("items"))
        generated_preview = [
            {"id": item.id, "text": (item.text or "")[:200]} for item in output_batch.items
        ]
        return NodeTraceSummary(
            inputs=[
                NodeTraceValue(
                    label="Source items", value=trace_items(input_batch.items), kind="items"
                ),
            ],
            outputs=[
                *llm_call_summary_values(
                    self.config,
                    mechanism=self._mechanism,
                    warnings=self._warnings,
                    retries=self._retries,
                    usage=output_batch.usage,
                ),
                NodeTraceValue(label="Generated texts", value=generated_preview),
                NodeTraceValue(
                    label="Generated items",
                    value=trace_items(output_batch.items),
                    kind="items",
                ),
            ],
        )
