changelog:
  exclude:
    labels:
      - skip-changelog
      - docs
      - ci
      - dependencies
      - chore
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: 🚨 Breaking changes
      labels:
        - breaking
    - title: ✨ Features
      labels:
        - feature
    - title: 🐛 Bug fixes
      labels:
        - fix
