name: ragworks

services:
  ragworks:
    image: ghcr.io/neeeser/ragworks:latest
    ports:
      - "7247:3000"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - document-storage:/data/storage
      - backend-config:/data/config

volumes:
  postgres-data:
  document-storage:
  backend-config:
